#!/bin/bash
export PROJECT_ENVIRONMENT="production"
export PROJECT_RANDOM_SETTING="12345"

# ELEMENTS_POST_PROCESS is a special variable to do post processing on elements
export ELEMENTS_POST_PROCESS=( 'example_post_process' 'hello_world' )

# Example of post processing the elements set above to create new elements
# for the templating engine to work with.
# Functions are prefixed with '_decompose-elements-'
_decompose-elements-example_post_process() {
  # Set a new element
  export POST_PROCESSED="Testing 123"

  # Do some complicated logic (or not so much)
  if [ "$PROJECT_ENVIRONMENT" == "production" ]; then
    export PRODUCTION=true
  else
    export DEVELOPMENT=true
  fi
}

# Just prints 'Hello World!' when uncommented out
_decompose-elements-hello_world() {
  #echo "Hello World!"
}
