#!/bin/bash

DECOMPOSE_PROCESSES=('hello_world' 'params' 'root_directory' 'environment')

# Prefix process names with '_decompose-process-' to avoid naming collisions

_decompose-process-hello_world() {
  echo "Hello World!"
}

_decompose-process-hello_world_help() {
  cat <<HELP_EOF
  Hello World Help
  This is an example help file
  Notice the indentions
HELP_EOF
}

_decompose-process-params() {
  echo "$@"
  echo $4
}

_decompose-process-params_help() {
  echo "  Prints parameters"
}

_decompose-process-root_directory() {
  local project_root_dir
  _decompose-project-root project_root_dir

  echo $project_root_dir
}

_decompose-process-root_directory_help() {
  echo "  Prints the project root directory"
}

_decompose-process-environment() {
  echo $PROJECT_ENVIRONMENT
}

_decompose-process-environment_help() {
  echo "  Print current environment"
}
